gnome-settings-daemon
compiz --sm-client-id $DESKTOP_AUTOSTART &
#/usr/lib/gnome-disk-utility/gdu-notification-daemon &
#/usr/lib/gnome-volume-manager/gnome-volume-manager
#python -u /usr/share/screenlets/Windowlist/WindowlistScreenlet.py &
#python -u /home/dank/src/facebook-notify/facebook-notify.py &
#screenlets-daemon &
gnome-screensaver
/home/dank/bin/start &
gmpc --start-hidden &
mail-notification &
wpa-gui -t &
exec avant-window-navigator
