#!/usr/bin/env bash

i=0
while read line ; do
	if [ $i -eq 0 ] ; then
		echo -n \"$line\",
	elif [ $i -eq 1 ] ; then
		# we're not emitting a "second address line"
		echo -n \"$line\",,
	else
		foo=$(echo "$line" | cut -d, -f1)
		bar=$(echo "$line" | cut -d, -f2 | cut -d' ' -f2)
		baz=$(echo "$line" | cut -d, -f2 | cut -d' ' -f3)
		echo $foo,$bar,$baz
	fi
	i=$((i + 1))
	i=$((i % 3))
done
