[Desktop Entry]
Name=danktheme
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Glossy
MetacityTheme=MurrineRoundedLessFramedIcon
IconTheme=SphereCrystal
GtkColorScheme=fg_color:#000000000000,bg_color:#edede9e9e3e3,text_color:#000000000000,base_color:#ffffffffffff,selected_fg_color:#ffffffffffff,selected_bg_color:#47446b85471c,tooltip_fg_color:#000000000000,tooltip_bg_color:#72adb1e8366e
CursorTheme=DMZ-Black
CursorSize=24
NotificationTheme=standard
