[Desktop Entry]
Name=danktheme
Type=X-GNOME-Metatheme
Comment=Nick Black (96x96 DPI @ 1920x1080)

[X-GNOME-Metatheme]
GtkTheme=MurrinaChrome
MetacityTheme=Glossy
IconTheme=Gion
GtkColorScheme=fg_color:#050505,bg_color:#E1ECF9,base_color:#FFFFFF,text_color:#000000,selected_bg_color:#95BEF0,selected_fg_color:#FFFFFF,tooltip_bg_color:#F5F5C9,tooltip_fg_color:#000000
CursorTheme=DMZ-Black
CursorSize=24
NotificationTheme=standard
